steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sec-460-devsecops/Sec460-Final', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sec-460-devsecops/Sec460-Final']

images:
  - 'gcr.io/sec-460-devsecops/Sec460-Final'
options:
  logging: CLOUD_LOGGING_ONLY